---
# ###############################################################
#  ____  _   _    ____ _           _
# / ___|| | | |  / ___| |_   _ ___| |_ ___ _ __
# \___ \| |_| | | |   | | | | / __| __/ _ \ '__|
#  ___) |  _  | | |___| | |_| \__ \ ||  __/ |
# |____/|_| |_|  \____|_|\__,_|___/\__\___|_|
# ###############################################################
- hosts: standalone
  vars:
    app_staging_dir: "/tmp/splunk-app-staging/{{ inventory_hostname }}"
    deploy_become_user: splunk

  tasks:
    - ansible.builtin.include_tasks: tasks/deploy_apps.yml
