---
# ###############################################################
#   _____    _____   _  _      _____
#  / ____|  / ____| | || |    / ____|
# | (___   | |      | || |_  | (___
#  \___ \  | |      |__   _|  \___ \
#  ____) | | |____     | |    ____) |
# |_____/   \_____|    |_|   |_____/
# ###############################################################
sc4s_splunk_dest: /opt
apps:
  - name: your_app_name
