[install]
is_configured = 1
state = enabled

[ui]
is_visible = 0
label = Org Frozen App

[launcher]
author = Seynur
description = coldToFrozen scripts: archive rawdata/journal* (+ l2hash) via SCP, S3, or GCS; logs to frozen_app.log / _internal.
version = 1.0.0

[package]
id = org_frozen_app
